<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@include file="/WEB-INF/common/tags.jsp" %>
<!doctype html>
<html lang="ko">
<head>
    <%@include file="/WEB-INF/common/common.jsp" %>
</head>
<body>
<%@include file="/WEB-INF/common/nav.jsp" %>
<div class="container-xxl text-center" id="wrap" style="gap:10px; width: 100%;">
    <div class="row p-3 justify-content-center">
        <div class="col mb-3">
            <h2>게시판</h2>
        </div>
    </div>
    <div class="row row-cols-2 row-cols-lg-5 g-2 g-lg-3">
        <div class="col ">
            <a class="nav-link p-3 border-start border-primary border-4 bg-light" style="border-color: #0064FF;"
               href="#">러닝화</a>
        </div>
        <div class="col ">
            <a class="nav-link p-3 border-start border-primary border-4 bg-light" style="border-color: #0064FF;"
               href="#">러닝복</a>
        </div>
        <div class="col ">
            <a class="nav-link p-3 border-start border-primary border-4 bg-light" style="border-color: #0064FF;"
               href="#">러닝용품</a>
        </div>
    </div>
    <div class="row p-3 d-flex justify-content-center">
        <div class="col-2">
            <select class="form-control" name="opt">
                <option value="name"> 상품명</option>
                <option value="maker"> 제조회사</option>
                <option value="minPrice"> 최소가격</option>
                <option value="maxPrice"> 최대가격</option>
            </select>
        </div>
        <div class="col-4">
            <input type="text" class="form-control" name="value" value="">
        </div>
        <div class="col-1">
            <button class="btn btn-outline-primary">검색</button>
        </div>
        <div class="col-1">
        </div>
    </div>
    <div class="row p-3">
        <table class="table">
            <colgroup>
                <col width="10%">
                <col width="*%">
                <col width="10%">
                <col width="10%">
                <col width="10%">
            </colgroup>
            <thead class="text-start">
            <tr>
                <th>
                    분류
                </th>
                <th>
                    제목
                </th>
                <th>
                    작성자
                </th>
                <th>
                    작성일
                </th>
                <th>
                    조회수
                </th>
            </tr>
            </thead>
            <tbody class="text-start">
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            <tr>
                <td>
                    운동
                </td>
                <td>
                    안녕하세요
                </td>
                <td>
                    홍길동
                </td>
                <td>
                    2024-10-30
                </td>
                <td>
                    10
                </td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="row p-3">
        <div class="col d-flex justify-content-end">
            <button class="btn btn-primary">글쓰기</button>
        </div>
    </div>
</div>
<%@include file="/WEB-INF/common/footer.jsp" %>
</body>
</html>
